#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# npm test
protected_branches=("master" "develop")
current_branch=$(git branch --show-current)

for branch in "${protected_branches[@]}"; do
  if [[ "$current_branch" == "$branch" ]]; then
    echo "You can't commit directly to $branch branch. Please create your own branch and use PR"
    exit 1
  fi
done

npx lint-staged